library(bruceR)
library(vars)
data(Canada)
VARselect(Canada)
vm <- VAR(Canada, p=3)
model_summary(vm)
granger_causality(vm)


## Loading data

YB_day <- read.csv("C:/Users/User/Desktop/용봉 일별 (2013~2022).csv", sep=",", header=T)
YB_day$WT <- as.numeric(YB_day$WT)
YB_day$pH <- as.numeric(YB_day$pH)
YB_day$EC <- as.numeric(YB_day$EC)
YB_day$DO <- as.numeric(YB_day$DO)
YB_day$TOC <- as.numeric(YB_day$TOC)
YB_day$TN <- as.numeric(YB_day$TN)
YB_day$TP <- as.numeric(YB_day$TP)
YB_day$Chla <- as.numeric(YB_day$Chla)
YB_day_rainy <- YB_day[YB_day$pct > 10,]
YB_day_norainy <- YB_day[YB_day$pct <= 10,]

NJ_day <- read.csv("C:/Users/User/Desktop/나주 일별 (2013~2022).csv", sep=",", header=T)
NJ_day$WT <- as.numeric(NJ_day$WT)
NJ_day$pH <- as.numeric(NJ_day$pH)
NJ_day$EC <- as.numeric(NJ_day$EC)
NJ_day$DO <- as.numeric(NJ_day$DO)
NJ_day$TB <- as.numeric(NJ_day$TB)
NJ_day$TOC <- as.numeric(NJ_day$TOC)
NJ_day$TN <- as.numeric(NJ_day$TN)
NJ_day$TP <- as.numeric(NJ_day$TP)
NJ_day$Chla <- as.numeric(NJ_day$Chla)
NJ_day_rainy <- NJ_day[NJ_day$pct > 10,]
NJ_day_norainy <- NJ_day[NJ_day$pct <= 10,]

YB_hour <- read.csv("C:/Users/User/Desktop/용봉 시간별 (2013~2022).csv", sep=",", header=T)
YB_hour$WT <- as.numeric(YB_hour$WT)
YB_hour$pH <- as.numeric(YB_hour$pH)
YB_hour$EC <- as.numeric(YB_hour$EC)
YB_hour$DO <- as.numeric(YB_hour$DO)
YB_hour$TOC <- as.numeric(YB_hour$TOC)
YB_hour$TN <- as.numeric(YB_hour$TN)
YB_hour$TP <- as.numeric(YB_hour$TP)
YB_hour$Chla <- as.numeric(YB_hour$Chla)

NJ_hour <- read.csv("C:/Users/User/Desktop/나주 시간별 (2013~2022).csv", sep=",", header=T)
NJ_hour$WT <- as.numeric(NJ_hour$WT)
NJ_hour$pH <- as.numeric(NJ_hour$pH)
NJ_hour$EC <- as.numeric(NJ_hour$EC)
NJ_hour$DO <- as.numeric(NJ_hour$DO)
NJ_hour$TB <- as.numeric(NJ_hour$TB)
NJ_hour$TOC <- as.numeric(NJ_hour$TOC)
NJ_hour$TN <- as.numeric(NJ_hour$TN)
NJ_hour$TP <- as.numeric(NJ_hour$TP)
NJ_hour$Chla <- as.numeric(NJ_hour$Chla)


## Granger causality test

library(lmtest)
grangertest(WT ~ pct, na.action=na.omit, data=YB_day)
grangertest(pH ~ pct, na.action=na.omit, data=YB_day)
grangertest(EC ~ pct, na.action=na.omit, data=YB_day)
grangertest(DO ~ pct, na.action=na.omit, data=YB_day)
grangertest(TOC ~ pct, na.action=na.omit, data=YB_day)
grangertest(TN ~ pct, na.action=na.omit, data=YB_day)
grangertest(TP ~ pct, na.action=na.omit, data=YB_day)
grangertest(Chla ~ pct, na.action=na.omit, data=YB_day)

grangertest(WT ~ pct, na.action=na.omit, data=YB_hour)
grangertest(pH ~ pct, na.action=na.omit, data=YB_hour)
grangertest(EC ~ pct, na.action=na.omit, data=YB_hour)
grangertest(DO ~ pct, na.action=na.omit, data=YB_hour)
grangertest(TOC ~ pct, na.action=na.omit, data=YB_hour)
grangertest(TN ~ pct, na.action=na.omit, data=YB_hour)
grangertest(TP ~ pct, na.action=na.omit, data=YB_hour)
grangertest(Chla ~ pct, na.action=na.omit, data=YB_hour)

#----------------------------------------------------------------

grangertest(WT ~ pct, na.action=na.omit, data=NJ_day)
grangertest(pH ~ pct, na.action=na.omit, data=NJ_day)
grangertest(EC ~ pct, na.action=na.omit, data=NJ_day)
grangertest(DO ~ pct, na.action=na.omit, data=NJ_day)
grangertest(TB ~ pct, na.action=na.omit, data=NJ_day)
grangertest(TOC ~ pct, na.action=na.omit, data=NJ_day)
grangertest(TN ~ pct, na.action=na.omit, data=NJ_day)
grangertest(TP ~ pct, na.action=na.omit, data=NJ_day)
grangertest(Chla ~ pct, na.action=na.omit, data=NJ_day)

grangertest(WT ~ pct, na.action=na.omit, data=NJ_hour)
grangertest(pH ~ pct, na.action=na.omit, data=NJ_hour)
grangertest(EC ~ pct, na.action=na.omit, data=NJ_hour)
grangertest(DO ~ pct, na.action=na.omit, data=NJ_hour)
grangertest(TB ~ pct, na.action=na.omit, data=NJ_hour)
grangertest(TOC ~ pct, na.action=na.omit, data=NJ_hour)
grangertest(TN ~ pct, na.action=na.omit, data=NJ_hour)
grangertest(TP ~ pct, na.action=na.omit, data=NJ_hour)
grangertest(Chla ~ pct, na.action=na.omit, data=NJ_hour)

#----------------------------------------------------------------

grangertest(WT ~ pct, na.action=na.omit, data=YB_day_rainy)
grangertest(pH ~ pct, na.action=na.omit, data=YB_day_rainy)
grangertest(EC ~ pct, na.action=na.omit, data=YB_day_rainy)
grangertest(DO ~ pct, na.action=na.omit, data=YB_day_rainy)
grangertest(TOC ~ pct, na.action=na.omit, data=YB_day_rainy)
grangertest(TN ~ pct, na.action=na.omit, data=YB_day_rainy)
grangertest(TP ~ pct, na.action=na.omit, data=YB_day_rainy)
grangertest(Chla ~ pct, na.action=na.omit, data=YB_day_rainy)

grangertest(WT ~ pct, na.action=na.omit, data=YB_day_norainy)
grangertest(pH ~ pct, na.action=na.omit, data=YB_day_norainy)
grangertest(EC ~ pct, na.action=na.omit, data=YB_day_norainy)
grangertest(DO ~ pct, na.action=na.omit, data=YB_day_norainy)
grangertest(TOC ~ pct, na.action=na.omit, data=YB_day_norainy)
grangertest(TN ~ pct, na.action=na.omit, data=YB_day_norainy)
grangertest(TP ~ pct, na.action=na.omit, data=YB_day_norainy)
grangertest(Chla ~ pct, na.action=na.omit, data=YB_day_norainy)

#----------------------------------------------------------------

grangertest(WT ~ pct, na.action=na.omit, data=NJ_day_rainy)
grangertest(pH ~ pct, na.action=na.omit, data=NJ_day_rainy)
grangertest(EC ~ pct, na.action=na.omit, data=NJ_day_rainy)
grangertest(DO ~ pct, na.action=na.omit, data=NJ_day_rainy)
grangertest(TB ~ pct, na.action=na.omit, data=NJ_day_rainy)
grangertest(TOC ~ pct, na.action=na.omit, data=NJ_day_rainy)
grangertest(TN ~ pct, na.action=na.omit, data=NJ_day_rainy)
grangertest(TP ~ pct, na.action=na.omit, data=NJ_day_rainy)
grangertest(Chla ~ pct, na.action=na.omit, data=NJ_day_rainy)

grangertest(WT ~ pct, na.action=na.omit, data=NJ_day_norainy)
grangertest(pH ~ pct, na.action=na.omit, data=NJ_day_norainy)
grangertest(EC ~ pct, na.action=na.omit, data=NJ_day_norainy)
grangertest(DO ~ pct, na.action=na.omit, data=NJ_day_norainy)
grangertest(TB ~ pct, na.action=na.omit, data=NJ_day_norainy)
grangertest(TOC ~ pct, na.action=na.omit, data=NJ_day_norainy)
grangertest(TN ~ pct, na.action=na.omit, data=NJ_day_norainy)
grangertest(TP ~ pct, na.action=na.omit, data=NJ_day_norainy)
grangertest(Chla ~ pct, na.action=na.omit, data=NJ_day_norainy)


## Cointegration test

library(ggplot2)
library(gridExtra)
v1 <- ggplot(aes(x=date, y=pct), data=YB) + geom_area(fill="red", alpha=0.5)
v2 <- ggplot(aes(x=date, y=WT), data=YB) + geom_area(fill="blue", alpha=0.5)
v3 <- ggplot(aes(x=date, y=pH), data=YB) + geom_area(fill="yellow", alpha=0.5)
v4 <- ggplot(aes(x=date, y=EC), data=YB) + geom_area(fill="green", alpha=0.5)
v5 <- ggplot(aes(x=date, y=DO), data=YB) + geom_area(fill="brown", alpha=0.5)
v6 <- ggplot(aes(x=date, y=TOC), data=YB) + geom_area(fill="purple", alpha=0.5)
v7 <- ggplot(aes(x=date, y=TN), data=YB) + geom_area(fill="orange", alpha=0.5)
v8 <- ggplot(aes(x=date, y=TP), data=YB) + geom_area(fill="pink", alpha=0.5)
v9 <- ggplot(aes(x=date, y=Chla), data=YB) + geom_area(fill="grey", alpha=0.5)
grid.arrange(v1, v2, v3, v4, v5, v6, v7, v8, v9, ncol=1)

library(aTSA)
coint.test(YB_day$WT, YB_day$pct, output=T)
coint.test(YB_day$pH, YB_day$pct, output=T)
coint.test(YB_day$EC, YB_day$pct, output=T)
coint.test(YB_day$DO, YB_day$pct, output=T)
coint.test(YB_day$TOC, YB_day$pct, output=T)
coint.test(YB_day$TN, YB_day$pct, output=T)
coint.test(YB_day$TP, YB_day$pct, output=T)
coint.test(YB_day$Chla, YB_day$pct, output=T)

coint.test(YB_hour$WT, YB_hour$pct, output=T)
coint.test(YB_hour$pH, YB_hour$pct, output=T)
coint.test(YB_hour$EC, YB_hour$pct, output=T)
coint.test(YB_hour$DO, YB_hour$pct, output=T)
coint.test(YB_hour$TOC, YB_hour$pct, output=T)
coint.test(YB_hour$TN, YB_hour$pct, output=T)
coint.test(YB_hour$TP, YB_hour$pct, output=T)
coint.test(YB_hour$Chla, YB_hour$pct, output=T)

coint.test(NJ_day$WT, NJ_day$pct, output=T)
coint.test(NJ_day$pH, NJ_day$pct, output=T)
coint.test(NJ_day$EC, NJ_day$pct, output=T)
coint.test(NJ_day$DO, NJ_day$pct, output=T)
coint.test(NJ_day$TB, NJ_day$pct, output=T)
coint.test(NJ_day$TOC, NJ_day$pct, output=T)
coint.test(NJ_day$TN, NJ_day$pct, output=T)
coint.test(NJ_day$TP, NJ_day$pct, output=T)
coint.test(NJ_day$Chla, NJ_day$pct, output=T)

coint.test(NJ_hour$WT, NJ_hour$pct, output=T)
coint.test(NJ_hour$pH, NJ_hour$pct, output=T)
coint.test(NJ_hour$EC, NJ_hour$pct, output=T)
coint.test(NJ_hour$DO, NJ_hour$pct, output=T)
coint.test(NJ_hour$TB, NJ_hour$pct, output=T)
coint.test(NJ_hour$TOC, NJ_hour$pct, output=T)
coint.test(NJ_hour$TN, NJ_hour$pct, output=T)
coint.test(NJ_hour$TP, NJ_hour$pct, output=T)
coint.test(NJ_hour$Chla, NJ_hour$pct, output=T)
